services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
  db:
    image: mariadb:${MOODLE_DOCKER_DB_VERSION:-10.7}
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
              --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: root
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: moodle
    volumes:
      - ./MoodleSQL.sql:/docker-entrypoint-initdb.d/MoodleSQL.sql